apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxdaemon
  namespace: daemon
  labels:
    k8s-app: nginxdaemon
spec:
  selector:
    matchLabels:
      name: nginxdaemon
  template:
    metadata:
      labels:
        name: nginxdaemon
    spec:
      containers:
      - name: nginx
        image: registry.tanzu.dk/msoderberg/nginx:1.24

