apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mydb
  name: mydb
  namespace: mariadb
spec:
  containers:
  - image: registry.tanzu.dk/msoderberg/mariadb
    name: mydb
    resources:
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: password
  imagePullSecrets:
  - name: dockersecret
  dnsPolicy: ClusterFirst
  restartPolicy: Always

