apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynginx
  name: mynginx-2
  namespace: production
spec:
  containers:
  - image: registry.tanzu.dk/msoderberg/nginx:1.24
    name: mynginx-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
