apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-nginx
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      resources:
      containers:
      - image: registry.tanzu.dk/msoderberg/nginx:1.24
        name: my-nginx
        ports:
        - containerPort: 8080
