apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: my-nginx
  namespace: default 
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-nginx
