apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
  namespace: secret
spec:
  restartPolicy: OnFailure
  containers:
  - args:
    - sleep
    - "3600"
    image: registry.tanzu.dk/busy-box/busybox
    name: secret-pod
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
